total_memory_limit = "2GB"

[[module]]
name = "cioSigner"
load_from = "/home/joera/Documents/dsg/fluence/target/wasm32-wasi/release/cioSigner.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/cioSigner/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/cioSigner/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/cioSigner/modules/cioSigner/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/cioSigner/modules/cioSigner/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"
