total_memory_limit = "2GB"

[[module]]
name = "dsgContent"
load_from = "/home/joera/Documents/dsg/fluence/target/wasm32-wasi/release/dsgContent.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgContent/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgContent/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgContent/modules/dsgContent/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgContent/modules/dsgContent/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"
