total_memory_limit = "2GB"

[[module]]
name = "dsgLeader"
load_from = "/home/joera/Documents/dsg/fluence/target/wasm32-wasi/release/dsgLeader.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgLeader/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgLeader/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgLeader/modules/dsgLeader/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgLeader/modules/dsgLeader/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"
