total_memory_limit = "2GB"

[[module]]
name = "dsgRenderer"
load_from = "/home/joera/Documents/dsg/fluence/target/wasm32-wasi/release/dsgRenderer.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgRenderer/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgRenderer/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgRenderer/modules/dsgRenderer/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/dsgRenderer/modules/dsgRenderer/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"
