total_memory_limit = "2GB"

[[module]]
name = "curl_effector"
load_from = "/home/joera/Documents/dsg/fluence/src/services/nPublication/modules/curl-effector/curl_effector.wasm"

  [module.mounted_binaries]
  ipfs = "/usr/bin/curl"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/modules/curl_effector/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/modules/curl_effector/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"

[[module]]
name = "facade"
load_from = "/home/joera/Documents/dsg/fluence/target/wasm32-wasi/release/facade.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/modules/facade/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/nPublication/modules/facade/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"
