total_memory_limit = "2GB"

[[module]]
name = "curl_effector"
load_from = "/home/joera/Documents/dsg/fluence/src/services/tuDsgWebHost/modules/cio-curl-effector/curl_effector.wasm"

  [module.mounted_binaries]
  ipfs = "/usr/bin/curl"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/modules/curl_effector/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/modules/curl_effector/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"

[[module]]
name = "tuDsgWebHost"
load_from = "/home/joera/Documents/dsg/fluence/target/wasm32-wasi/release/tuDsgWebHost.wasm"

[module.wasi.mapped_dirs]
"/tmp" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/service/tmp"
"/storage" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/service/storage"
"/tmp/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/modules/tuDsgWebHost/tmp/module"
"/storage/module" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/services/tuDsgWebHost/modules/tuDsgWebHost/storage/module"
"/tmp/vault" = "/home/joera/Documents/dsg/fluence/.fluence/tmp/volumes/particles"
